/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './app/**/*.{js,jsx,ts,tsx}',
    './src/**/*.{js,jsx,ts,tsx}',
    './constants/**/*.{js,jsx,ts,tsx}',
  ],
  presets: [require('nativewind/preset')],
  theme: {
    extend: {
      colors: {
        background: '#F1F8E9',
        card: '#FFFFFF',
        primary: '#2E7D32',
        primaryLight: '#4CAF50',
        primaryDark: '#1B5E20',
        amber: '#FFA000',
        amberLight: '#FFF3E0',
        red: '#E53935',
        redLight: '#FFEBEE',
        text: '#1A1A1A',
        textSecondary: '#6B7280',
        textMuted: '#9CA3AF',
        border: '#E8F5E9',
        borderLight: '#F0F0F0',
        shadow: '#000000',
        white: '#FFFFFF',
        completed: '#C8E6C9',
        indicaBadge: '#E8F5E9',
        sativaBadge: '#FFFDE7',
        hybridBadge: '#F3E5F5',

        // Dark Mode
        'dark-bg': '#0A1410',
        'dark-bg-elevated': '#1A2820',
        'dark-bg-card': '#1E2D24',
        'dark-border': '#2A3D32',
        'dark-border-bright': '#3D5A47',
        'primary-bright': '#00FF88',
        'text-primary-dark': '#E8F5E9',
        'text-secondary-dark': '#A5C9AD',
        'text-muted-dark': '#6B8A73',
        'text-disabled-dark': '#4A5D52',
        'success-dark': '#00FF88',
        'warning-dark': '#FFB74D',
        'error-dark': '#FF5252',
        'info-dark': '#64B5F6',
        'badge-indica': '#7B2CBF',
        'badge-sativa': '#FFB74D',
        'badge-hybrid': '#64B5F6',
      },
    },
  },
  plugins: [],
};
