/** Type-safe route constants for use with router.push / router.replace. */
export const ROUTES = {
  GARDEN: '/',
  GARDEN_PLANT_SELECTOR: '/plant-selector',
  GARDEN_LOG_ACTIVITY_ACTIONS: '/log-activity-actions',
  COMMUNITY: '/community',
  COMMUNITY_CREATE_POST: '/community/create-post',
  SCAN: '/scan',
  SCHEDULE: '/schedule',
  STRAINS: '/strains',
  ADD_PLANT: '/plants/add',
  ADD_PLANT_SUCCESS: '/plants/add-success',
  PLANT_DETAIL_PATHNAME: '/plants/[id]',
  PLANT_DETAIL: (id: string) => `/plants/${id}`,
  AI_DIAGNOSIS: '/ai-diagnosis',
  AGE_GATE: '/age-gate',
  ADD_NOTE: (plantId: string) => `/notes/add?plantId=${plantId}` as const,
  HARVEST: '/harvests/create',
  HARVEST_SUCCESS: '/harvests/success',
  CARE_LOG_CREATE: '/care-log/create',
  ONBOARDING: '/onboarding',
  PROFILE: '/profile',
  STRAIN_FAVORITES: '/strains/favorites',
  STRAIN_FILTERS: '/strains/filters',
  STRAIN_DETAIL_PATHNAME: '/strains/[id]',
  STRAIN_DETAIL: (id: string) => `/strains/${id}`,
  TASK_DETAIL_GARDEN_PATHNAME: '/tasks/[id]',
  TASK_DETAIL_GARDEN: (id: string) => `/tasks/${id}`,
  TASK_DETAIL_SCHEDULE_PATHNAME: '/schedule/tasks/[id]',
  TASK_DETAIL_SCHEDULE: (id: string) => `/schedule/tasks/${id}`,
  WELCOME: '/welcome',
} as const;
